### PR TITLE
Improved test coverage

### PR DESCRIPTION
**Pull request by scott113341**

### CODE REVIEW

**Comment by mmedal** [comment]
lol, that's pretty funny. I just did this too

**Comment by mmedal** [comment]
i was like, "what is this garbage, non-100% test coverage?"

**Comment by scott113341** [comment]
For some reason the badge still shows 94%, even though if you click on it it shows 100%

**Comment by mmedal** [comment]
it's just caching, it's fine

**Comment by rtsao** [comment]
Yeah, for some reason the coveralls badges seem to stay cached for a while

**Pull request merged**
